Repository autosarzs/Dev, pull requests merged in 2019-12, with the labels that each got.

#47 DevCan_Can_SetControllerModeFix_1
  Software/bsw/static/Mcal/CAN/src/Can.c
Labels: bug

#49 Cleaning configuration structures
  Software/bsw/gen/Can_Cfg.h
  Software/bsw/gen/Can_PBcfg.c
  Software/bsw/static/Mcal/CAN/inc/Can.h
  Software/bsw/static/Mcal/CAN/src/Can.c
  Software/build/IDEs/CCS/.gitignore
Labels: enhancement

#53 Can_Write_Fix PullReq
  Software/bsw/gen/Can_Cfg.h
  Software/bsw/static/Mcal/CAN/src/Can.c
Labels: bug, enhancement

#51 Fixed Some issues in Can_SetControllerMode Function
  Software/bsw/static/Mcal/CAN/src/Can.c
Labels: bug, enhancement

#52 Can main function read fix 41
  Software/bsw/gen/Can_Cfg.h
  Software/bsw/gen/Can_PBcfg.c
  Software/bsw/static/Infrastructure/inc/Can_GeneralTypes.h
  Software/bsw/static/Mcal/CAN/inc/Can.h
  Software/bsw/static/Mcal/CAN/src/Can.c
  Software/bsw/stub/stub.c
  Software/build/IDEs/CCS/.cproject
Labels: enhancement
